language: c
script: make && make fs.img
deploy:
  provider: releases
  api_key:
    secure: A/2ah12rJK1/Jokp4OVpos7+n96hbJ//C0rO6rFw0G4ncet+IvLpoR7+BWL91e9ullXEiP26P2LkdjpzTE/LcqBbJultwuy9lt1wdsYsyNL9X9ob862Xfw8ahwzqV4NeS2dDAXiO5zFwvxjWvOL4FWY0Il7fNq8mm5nT5dLlIVA3XwQdd+aeFPN+usIYBEuAB/B7oQzz1OKqrWvIyIdANDPDkNTvWGSx9kLu+dF/nt1ahaMLdY9RN3ViP/5qu9YCdj52h908vJx0z4dnCd1T4WS5qge9XRShJuvE90bFDr6lQTlnIuVNrV2Y2xwmHekgnzpf9+d67RDAmkHWQUVnkEkSpbfDKWImrI7RWoWMZEmrgR2XKQ3bYYMXHKIdEj1LAUlN8rbD4CM+aMjwc6PxUdD15/PaBhP1HqaEaZYjg9FCm8b0asTrSPW21KuLlSFhfPcVTtnztGMgvs+ZU3umi0SZ+cyVkp08BvF53+++2k4gjBU0g3EJFtLomYiTSOTettTYkowfXjVVTWfMS9h0H49VKhOMJKxapZ/Ny7ZbcNTMjzFv70BcLua5SZNb7aECYjGnRmRjfdL/Z4Jur3XD0BeUAtCi1E1xApjdo2lnntZitgUvcFtGo26ze7qHyWQvYjGdZvJpi51HuxNEydrtSMEjW5VrrzPsfv3OMf2WtQE=
  file: 
    - fs.img
    - xv6.img
  skip_cleanup: true
  on:
    repo: nmorozin/xv6-public
    branch: tarea1
    tags: true
